import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/nav';
import Footer from '@/components/footer';
import jsonColares from '@/data/colares.json';
import slugify from 'slugify';

const raleway = Raleway({
  variable: '--font-raleway',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Carmassi',
  description: 'Generated by create next app',
};

export const colaresData = jsonColares.map((item) => ({
  id: slugify(item.nome, { strict: true, lower: true }),
  ...item,
}));
export type IColaresData = (typeof colaresData)[0];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pt-BR'>
      <body className={`${raleway.variable} font-raleway tracking-widest`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
