import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/nav';

const raleway = Raleway({
  variable: '--font-raleway',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Carmassi',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pt-BR'>
      <body className={`${raleway.variable} font-raleway tracking-widest`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
